### ISSUE TITLE
current recv//nowait strategy allows stray icmp packets to disrupt future communication

### ISSUE THREAD

**Issue by ityonemo** [hauleth/gen_icmp#1]
by gating the recv on having a send triggered, you can have a situation where an ICMP response (perhaps a delayed response from an earlier send that was given up on) triggers the recv, mismatches, and then causes recv to be 'satisfied' and then you might never receive any packets at all.

might be better to have a timeout/recv-loop that waits for any message and can shoot off sends based on incoming messages during the wakeup period.  However, you might not be able to trivially use handle_continue with this because it doesn't admit handle_infos.

**Comment by hauleth** [comment]
Yes it will work like that, however see that it do not wait for response in `gen_icmp:ping/{3,4}`. The general use case is that user should send pings and wait for the responses in loop. Quite similar like it work with `gen_udp`. So example "pinging module" could look like:

```
-module(pinger).

-include_lib("kernel/include/logger.hrl").

-export([
  % …
]).

-behaviour(gen_server).

start_link() ->
  gen_server:start_link(?MODULE, [], []).

init(_) ->
  {ok, Socket} = gen_icmp:open(),
  ok = gen_icmp:ping(Socket, #{family => inet, addr => {127,0,0,1}}, <<"foobar">>, [{id, 42}]),
  {ok, Socket}.

% …

handle_info({icmp, _From, {echorep, #{id := 42, data := Data}}}, State) ->
  ?LOG_INFO("Received ~p~n", [Data]),
  {noreply, State}.
```

**Comment by hauleth** [comment]
The reason for such design is that with this approach user can send multiple echo requests and then accept them independently if they want. The matching then can be done by using ID and sequence no pairs.

**Comment by hauleth** [comment]
As there seems no more discussion and no problems emerged so far I am closing it. If you (or someone else) spot any problem there then I will reopen it.
